# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coffee.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63offee.proto\"\'\n\rCoffeeRequest\x12\x16\n\x0erequestJsonStr\x18\x01 \x01(\t\")\n\x0e\x43offeeResponse\x12\x17\n\x0fresponseJsonStr\x18\x01 \x01(\t28\n\x06\x43offee\x12.\n\x0bOrderCoffee\x12\x0e.CoffeeRequest\x1a\x0f.CoffeeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coffee_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COFFEEREQUEST._serialized_start=16
  _COFFEEREQUEST._serialized_end=55
  _COFFEERESPONSE._serialized_start=57
  _COFFEERESPONSE._serialized_end=98
  _COFFEE._serialized_start=100
  _COFFEE._serialized_end=156
# @@protoc_insertion_point(module_scope)
