# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server.proto.coffee_pb2 as coffee__pb2
# from . import coffee_pb2 as coffee__pb2

class CoffeeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrderCoffee = channel.unary_unary(
                '/Coffee/OrderCoffee',
                request_serializer=coffee__pb2.CoffeeRequest.SerializeToString,
                response_deserializer=coffee__pb2.CoffeeResponse.FromString,
                )


class CoffeeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OrderCoffee(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoffeeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrderCoffee': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderCoffee,
                    request_deserializer=coffee__pb2.CoffeeRequest.FromString,
                    response_serializer=coffee__pb2.CoffeeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Coffee', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coffee(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OrderCoffee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Coffee/OrderCoffee',
            coffee__pb2.CoffeeRequest.SerializeToString,
            coffee__pb2.CoffeeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
